
/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

*/



const findTheDifference = function(s, t) {
    const chars = new Map()
    for(const char of s){
        if(!chars.has(char)) chars.set(char, 0)
        chars.set(char, chars.get(char) + 1)
    }
    for(const char of t){
        if(!chars.get(char)) return char
        chars.set(char, chars.get(char) - 1)
    }
}